### ISSUE TITLE
Please check nodeport and clusterip

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/kubernetes#69]
After discussing with all team we have to clarify which service type we have to use for ingress controller. @alibek17  Please take a look at each services and make sure you document everything and come up with good solutions. 

Thank you

**Comment by alibek17** [comment]
We have created 4 pods, exposed 2 of them with ClusterIP service and 2 of them with NodePort service. If put behind an Nginx Ingress Controller all 4 of them are available from the internet, but if the Google's native ingress controller is used then the pods exposed by ClusterIP service are not available. 

Since NodePort service is working for both cases, the best way is to stay with the NodePort service. 

If anybody is curious and wants to see it working go to bastion.fuchicorp.com and follow the instructions below:

To create the pods:
```
kubectl run node1 --image=nginx --port=80 --restart=Never
kubectl run node2 --image=nginx --port=80 --restart=Never
kubectl run cluster1 --image=nginx --port=80 --restart=Never
kubectl run cluster2 --image=nginx --port=80 --restart=Never
```

To expose the pods:
```
kubectl expose pod cluster1 --port=80 --target-port=80
kubectl expose pod cluster2 --port=80 --target-port=80
kubectl expose pod node1 --type=NodePort --port=80 --target-port=80
kubectl expose pod node2 --type=NodePort --port=80 --target-port=80
```

To change the content served by web browser when you access the pods from the internet:
```
kubectl exec -it node1 -- /bin/bash
echo node1>/usr/share/nginx/html/index.html

kubectl exec -it node2 -- /bin/bash
echo node2>/usr/share/nginx/html/index.html

kubectl exec -it cluster1 -- /bin/bash
echo cluster1>/usr/share/nginx/html/index.html

kubectl exec -it cluster2 -- /bin/bash
echo cluster2>/usr/share/nginx/html/index.html
```
Create a yaml file for an ingress resource with a name ingress.yaml:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: check-ingress
spec:
  rules:
  - host: cluster1.check.com
    http:
      paths:
      - backend:
          serviceName: cluster1
          servicePort: 80
  - host: cluster2.check.com
    http:
      paths:
      - backend:
          serviceName: cluster2
          servicePort: 80
  - host: node1.check.com
    http:
      paths:
      - backend:
          serviceName: node1
          servicePort: 80
  - host: node2.check.com
    http:
      paths:
      - backend:
          serviceName: node2
          servicePort: 80
```
Create an ingress resource from the file above:
```
kubectl apply -f ingress.yaml
```

We will be using an nginx ingress controller created by Farkhod for the test purposes, so all our pods should be accessible.

The last step is to go to /etc/hosts file on your local machine and add the following lines:
```
34.66.105.106  cluster1.check.com
34.66.105.106  cluster2.check.com
34.66.105.106  node1.check.com
34.66.105.106  node2.check.com
```
